project:
  type: website
  output-dir: docs

website:
  title: "Teja Pristavec, PhD"
  favicon: favicon.ico
  google-analytics: "UA-91248100-1"

format:
  html:
    theme:
      light: lumen
      dark: solar
    css: styles.css
    toc: true

editor: visual


